//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClg
{
    using System;
    using System.Collections.Generic;
    
    public partial class direcciones
    {
        public long id { get; set; }
        public long clienteid { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public string colonia { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
